export const tree = {
  id: 'who_-_suspected_covid-19_assessment.v0',
  name: 'WHO - Suspected Covid-19 assessment.v0',
  localizedName: 'WHO - Suspected Covid-19 assessment.v0',
  rmType: 'COMPOSITION',
  nodeId: 'openEHR-EHR-COMPOSITION.encounter.v1',
  min: 1,
  max: 1,
  localizedNames: { en: 'WHO - Suspected Covid-19 assessment.v0' },
  localizedDescriptions: { en: 'Interaction, contact or care event between a subject of care and healthcare provider(s).' },
  aqlPath: '',
  children: [{
    id: 'context',
    rmType: 'EVENT_CONTEXT',
    min: 1,
    max: 1,
    aqlPath: '/context',
    children: [{
      id: 'start_time',
      name: 'Start_time',
      rmType: 'DV_DATE_TIME',
      min: 1,
      max: 1,
      aqlPath: '/context/start_time',
      inputs: [{ type: 'DATETIME' }],
      inContext: true,
    }, {
      id: 'setting',
      name: 'Setting',
      rmType: 'DV_CODED_TEXT',
      min: 1,
      max: 1,
      aqlPath: '/context/setting',
      inputs: [{
        suffix: 'code',
        type: 'TEXT',
      }, {
        suffix: 'value',
        type: 'TEXT',
      }],
      inContext: true,
    }],
  }, {
    id: 'reason_for_encounter',
    name: 'Reason for encounter',
    localizedName: 'Reason for encounter',
    rmType: 'EVALUATION',
    nodeId: 'openEHR-EHR-EVALUATION.reason_for_encounter.v1',
    min: 0,
    max: -1,
    localizedNames: { en: 'Reason for encounter' },
    localizedDescriptions: { en: 'The reason for initiation of any healthcare encounter or contact by the individual who is the subject of care.' },
    aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]',
    children: [{
      id: 'presenting_problem',
      name: 'Presenting problem',
      localizedName: 'Presenting problem',
      rmType: 'DV_TEXT',
      nodeId: 'at0004',
      min: 0,
      max: -1,
      localizedNames: { en: 'Presenting problem' },
      localizedDescriptions: { en: 'Identification of the clinical or social problem motivating the subject of care to seeking healthcare.' },
      annotations: { comment: 'Coding of the \'Presenting problem\' with a terminology is desirable, where possible. Clinical or social reasons for seeking healthcare can include health issues, symptoms or physical signs. Examples: health issues - desire to quit smoking, domestic violence; symptoms - abdominal pain, shortness of breath; physical signs - an altered conscious state. \'Chief complaint\' may be used as a valid synonym for \'Presenting problem\' in templates.\r\n ' },
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0004]/value',
      inputs: [{
        type: 'TEXT',
        defaultValue: 'Suspected Covid-19 infection',
      }],
    }, {
      id: 'language',
      name: 'Language',
      rmType: 'CODE_PHRASE',
      min: 1,
      max: 1,
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/language',
      inContext: true,
    }, {
      id: 'encoding',
      name: 'Encoding',
      rmType: 'CODE_PHRASE',
      min: 1,
      max: 1,
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/encoding',
      inContext: true,
    }, {
      id: 'subject',
      name: 'Subject',
      rmType: 'PARTY_PROXY',
      min: 1,
      max: 1,
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/subject',
      inContext: true,
    }],
  }, {
    id: 'symptoms',
    name: 'Symptoms',
    localizedName: 'Symptoms',
    rmType: 'SECTION',
    nodeId: 'openEHR-EHR-SECTION.adhoc.v1',
    min: 0,
    max: -1,
    localizedNames: { en: 'Symptoms' },
    localizedDescriptions: { en: 'A generic section header which should be renamed in a template to suit a specific clinical context.' },
    aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']',
    children: [{
      id: 'story_history',
      name: 'Story/History',
      localizedName: 'Story/History',
      rmType: 'OBSERVATION',
      nodeId: 'openEHR-EHR-OBSERVATION.story.v1',
      min: 0,
      max: 1,
      localizedNames: { en: 'Story/History' },
      localizedDescriptions: { en: 'The subjective clinical history of the subject of care as recorded directly by the subject, or reported to a clinician by the subject or a carer.' },
      aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]',
      children: [{
        id: 'story',
        name: 'Story',
        localizedName: 'Story',
        rmType: 'DV_TEXT',
        nodeId: 'at0004',
        min: 0,
        max: 1,
        localizedNames: { en: 'Story' },
        localizedDescriptions: { en: 'Narrative description of the story or clinical history for the subject of care.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value',
        inputs: [{ type: 'TEXT' }],
      }, {
        id: 'first_symptom',
        name: 'First symptom',
        localizedName: 'First symptom',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.symptom_sign.v1',
        min: 0,
        max: 1,
        localizedNames: { en: 'First symptom' },
        localizedDescriptions: { en: 'Reported observation of a physical or mental disturbance in an individual.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          localizedName: 'Symptom/Sign name',
          rmType: 'DV_TEXT',
          nodeId: 'at0001',
          min: 1,
          max: 1,
          localizedNames: { en: 'Symptom/Sign name' },
          localizedDescriptions: { en: 'The name of the reported symptom or sign.' },
          annotations: { comment: 'Symptom name should be coded with a terminology, where possible.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0001]/value',
          inputs: [{
            type: 'TEXT',
            defaultValue: 'First symptom',
          }],
          termBindings: {
            'SNOMED-CT': {
              value: '[SNOMED-CT::418799008]',
              terminologyId: 'SNOMED-CT',
            },
          },
        }, {
          id: 'episode_onset',
          name: 'Episode onset',
          localizedName: 'Episode onset',
          rmType: 'DV_DATE_TIME',
          nodeId: 'at0152',
          min: 0,
          max: 1,
          localizedNames: { en: 'Episode onset' },
          localizedDescriptions: { en: 'The onset for this episode of the symptom or sign.' },
          annotations: { comment: 'While partial dates are permitted, the exact date and time of onset can be recorded, if appropriate. If this symptom or sign is experienced for the first time or is a re-occurrence, this date is used to represent the onset of this episode. If this symptom or sign is ongoing, this data element may be redundant if it has been recorded previously.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0152]/value',
          inputs: [{ type: 'DATETIME' }],
        }],
      }, {
        id: 'cough',
        name: 'Cough',
        localizedName: 'Cough',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.symptom_sign.v1',
        min: 0,
        max: 1,
        localizedNames: { en: 'Cough' },
        localizedDescriptions: { en: 'Reported observation of a physical or mental disturbance in an individual.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          localizedName: 'Symptom/Sign name',
          rmType: 'DV_CODED_TEXT',
          nodeId: 'at0001',
          min: 1,
          max: 1,
          localizedNames: { en: 'Symptom/Sign name' },
          localizedDescriptions: { en: 'The name of the reported symptom or sign.' },
          annotations: { comment: 'Symptom name should be coded with a terminology, where possible.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']/items[at0001]/value',
          termBindings: {
            'SNOMED-CT': {
              value: '[SNOMED-CT::418799008]',
              terminologyId: 'SNOMED-CT',
            },
          },
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          localizedName: 'Nil significant',
          rmType: 'DV_BOOLEAN',
          nodeId: 'at0035',
          min: 0,
          max: 1,
          localizedNames: { en: 'Nil significant' },
          localizedDescriptions: { en: 'The identified symptom or sign was reported as not being present to any significant degree.' },
          annotations: { comment: 'Record as True if the subject of care has reported the symptom as not significant. For example: if the individual has never experienced the symptom it is appropriate to record \'nil significant\'; or if the individual commonly experiences the symptom, in some circumstances it may be considered appropriate to record \'nil significant\' if the individual has experienced no deviation from their \'normal\' baseline.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']/items[at0035]/value',
          inputs: [{
            type: 'BOOLEAN',
            list: [{
              value: 'true',
              label: 'true',
            }],
          }],
        }],
      }, {
        id: 'fever',
        name: 'Fever',
        localizedName: 'Fever',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.symptom_sign.v1',
        min: 0,
        max: 1,
        localizedNames: { en: 'Fever' },
        localizedDescriptions: { en: 'Reported observation of a physical or mental disturbance in an individual.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          localizedName: 'Symptom/Sign name',
          rmType: 'DV_CODED_TEXT',
          nodeId: 'at0001',
          min: 1,
          max: 1,
          localizedNames: { en: 'Symptom/Sign name' },
          localizedDescriptions: { en: 'The name of the reported symptom or sign.' },
          annotations: { comment: 'Symptom name should be coded with a terminology, where possible.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']/items[at0001]/value',
          termBindings: {
            'SNOMED-CT': {
              value: '[SNOMED-CT::418799008]',
              terminologyId: 'SNOMED-CT',
            },
          },
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          localizedName: 'Nil significant',
          rmType: 'DV_BOOLEAN',
          nodeId: 'at0035',
          min: 0,
          max: 1,
          localizedNames: { en: 'Nil significant' },
          localizedDescriptions: { en: 'The identified symptom or sign was reported as not being present to any significant degree.' },
          annotations: { comment: 'Record as True if the subject of care has reported the symptom as not significant. For example: if the individual has never experienced the symptom it is appropriate to record \'nil significant\'; or if the individual commonly experiences the symptom, in some circumstances it may be considered appropriate to record \'nil significant\' if the individual has experienced no deviation from their \'normal\' baseline.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']/items[at0035]/value',
          inputs: [{
            type: 'BOOLEAN',
            list: [{
              value: 'true',
              label: 'true',
            }],
          }],
        }],
      }, {
        id: 'sore_throat',
        name: 'Sore throat',
        localizedName: 'Sore throat',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.symptom_sign.v1',
        min: 0,
        max: 1,
        localizedNames: { en: 'Sore throat' },
        localizedDescriptions: { en: 'Reported observation of a physical or mental disturbance in an individual.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          localizedName: 'Symptom/Sign name',
          rmType: 'DV_CODED_TEXT',
          nodeId: 'at0001',
          min: 1,
          max: 1,
          localizedNames: { en: 'Symptom/Sign name' },
          localizedDescriptions: { en: 'The name of the reported symptom or sign.' },
          annotations: { comment: 'Symptom name should be coded with a terminology, where possible.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0001]/value',
          inputs: [{
            suffix: 'code',
            type: 'TEXT',
            defaultValue: '12345',
          }, {
            suffix: 'value',
            type: 'TEXT',
            defaultValue: 'Sore throat',
          }],
          termBindings: {
            'SNOMED-CT': {
              value: '[SNOMED-CT::418799008]',
              terminologyId: 'SNOMED-CT',
            },
          },
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          localizedName: 'Nil significant',
          rmType: 'DV_BOOLEAN',
          nodeId: 'at0035',
          min: 0,
          max: 1,
          localizedNames: { en: 'Nil significant' },
          localizedDescriptions: { en: 'The identified symptom or sign was reported as not being present to any significant degree.' },
          annotations: { comment: 'Record as True if the subject of care has reported the symptom as not significant. For example: if the individual has never experienced the symptom it is appropriate to record \'nil significant\'; or if the individual commonly experiences the symptom, in some circumstances it may be considered appropriate to record \'nil significant\' if the individual has experienced no deviation from their \'normal\' baseline.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0035]/value',
          inputs: [{
            type: 'BOOLEAN',
            list: [{
              value: 'true',
              label: 'true',
            }],
          }],
        }],
      }, {
        id: 'breathlessness',
        name: 'Breathlessness',
        localizedName: 'Breathlessness',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.symptom_sign.v1',
        min: 0,
        max: 1,
        localizedNames: { en: 'Breathlessness' },
        localizedDescriptions: { en: 'Reported observation of a physical or mental disturbance in an individual.' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          localizedName: 'Symptom/Sign name',
          rmType: 'DV_CODED_TEXT',
          nodeId: 'at0001',
          min: 1,
          max: 1,
          localizedNames: { en: 'Symptom/Sign name' },
          localizedDescriptions: { en: 'The name of the reported symptom or sign.' },
          annotations: { comment: 'Symptom name should be coded with a terminology, where possible.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0001]/value',
          inputs: [{
            suffix: 'code',
            type: 'TEXT',
            defaultValue: '12345',
          }, {
            suffix: 'value',
            type: 'TEXT',
            defaultValue: 'Dyspnoea',
          }],
          termBindings: {
            'SNOMED-CT': {
              value: '[SNOMED-CT::418799008]',
              terminologyId: 'SNOMED-CT',
            },
          },
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          localizedName: 'Nil significant',
          rmType: 'DV_BOOLEAN',
          nodeId: 'at0035',
          min: 0,
          max: 1,
          localizedNames: { en: 'Nil significant' },
          localizedDescriptions: { en: 'The identified symptom or sign was reported as not being present to any significant degree.' },
          annotations: { comment: 'Record as True if the subject of care has reported the symptom as not significant. For example: if the individual has never experienced the symptom it is appropriate to record \'nil significant\'; or if the individual commonly experiences the symptom, in some circumstances it may be considered appropriate to record \'nil significant\' if the individual has experienced no deviation from their \'normal\' baseline.' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0035]/value',
          inputs: [{
            type: 'BOOLEAN',
            list: [{
              value: 'true',
              label: 'true',
            }],
          }],
        }],
      }, {
        id: 'time',
        name: 'Time',
        rmType: 'DV_DATE_TIME',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/time',
        inputs: [{ type: 'DATETIME' }],
        inContext: true,
      }, {
        id: 'language',
        name: 'Language',
        rmType: 'CODE_PHRASE',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/language',
        inContext: true,
      }, {
        id: 'encoding',
        name: 'Encoding',
        rmType: 'CODE_PHRASE',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/encoding',
        inContext: true,
      }, {
        id: 'subject',
        name: 'Subject',
        rmType: 'PARTY_PROXY',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/subject',
        inContext: true,
      }],
    }],
  }, {
    id: 'travel_history',
    name: 'Travel history',
    localizedName: 'Travel history',
    rmType: 'SECTION',
    nodeId: 'openEHR-EHR-SECTION.adhoc.v1',
    min: 0,
    max: 1,
    localizedNames: { en: 'Travel history' },
    localizedDescriptions: { en: 'A generic section header which should be renamed in a template to suit a specific clinical context.' },
    aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']',
    children: [{
      id: 'trip_details',
      name: 'Trip details',
      localizedName: 'Trip details',
      rmType: 'OBSERVATION',
      nodeId: 'openEHR-EHR-OBSERVATION.travel_history.v0',
      min: 0,
      max: 1,
      localizedNames: { en: 'Trip details' },
      localizedDescriptions: { en: 'travel history' },
      aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]',
      children: [{
        id: 'duration_of_travel',
        name: 'Duration of travel',
        localizedName: 'Duration of travel',
        rmType: 'DV_DURATION',
        nodeId: 'at0070',
        min: 0,
        max: 1,
        localizedNames: { en: 'Duration of travel' },
        localizedDescriptions: { en: '*' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0070]/value',
        inputs: [{
          suffix: 'year',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'month',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'day',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'week',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'hour',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'minute',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }, {
          suffix: 'second',
          type: 'INTEGER',
          validation: {
            range: {
              minOp: '>=',
              min: 0,
            },
          },
          defaultValue: 0,
        }],
      }, {
        id: 'date_of_return_to_uk',
        name: 'Date of return to UK',
        localizedName: 'Date of return to UK',
        rmType: 'DV_DATE_TIME',
        nodeId: 'at0071',
        min: 0,
        max: 1,
        localizedNames: { en: 'Date of return to UK' },
        localizedDescriptions: { en: '*' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0071,\'Date of return to UK\']/value',
        inputs: [{ type: 'DATETIME' }],
      }, {
        id: 'covid19_exposure',
        name: 'Covid19 exposure',
        localizedName: 'Covid19 exposure',
        rmType: 'CLUSTER',
        nodeId: 'openEHR-EHR-CLUSTER.covid19_exposure.v0',
        min: 0,
        max: -1,
        localizedNames: { en: 'Covid19 exposure' },
        localizedDescriptions: { en: 'Covid19 exposure' },
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]',
        children: [{
          id: 'incubation_period',
          name: 'Incubation period',
          localizedName: 'Incubation period',
          rmType: 'DV_DURATION',
          nodeId: 'at0001',
          min: 0,
          max: 1,
          localizedNames: { en: 'Incubation period' },
          localizedDescriptions: { en: '*' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0001]/value',
          inputs: [{
            suffix: 'year',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'month',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'day',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'week',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'hour',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'minute',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }, {
            suffix: 'second',
            type: 'INTEGER',
            validation: {
              range: {
                minOp: '>=',
                min: 0,
              },
            },
            defaultValue: 0,
          }],
        }, {
          id: 'contact_with_confirmed_case',
          name: 'Contact with confirmed case',
          localizedName: 'Contact with confirmed case',
          rmType: 'DV_CODED_TEXT',
          nodeId: 'at0002',
          min: 0,
          max: 1,
          localizedNames: { en: 'Contact with confirmed case' },
          localizedDescriptions: { en: '*' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0002]/value',
          inputs: [{
            suffix: 'code',
            type: 'CODED_TEXT',
            list: [{
              value: 'at0003',
              label: 'Yes',
              localizedLabels: { en: 'Yes' },
              localizedDescriptions: { en: '*' },
            }, {
              value: 'at0004',
              label: 'No',
              localizedLabels: { en: 'No' },
              localizedDescriptions: { en: '*' },
            }, {
              value: 'at0005',
              label: 'Unknown',
              localizedLabels: { en: 'Unknown' },
              localizedDescriptions: { en: '*' },
            }],
          }],
        }, {
          id: 'outbreak',
          name: 'Outbreak',
          localizedName: 'Outbreak',
          rmType: 'CLUSTER',
          nodeId: 'at0006',
          min: 0,
          max: -1,
          localizedNames: { en: 'Outbreak' },
          localizedDescriptions: { en: '*' },
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]',
          children: [{
            id: 'area',
            name: 'Area',
            localizedName: 'Area',
            rmType: 'DV_CODED_TEXT',
            nodeId: 'at0007',
            min: 0,
            max: 1,
            localizedNames: { en: 'Area' },
            localizedDescriptions: { en: '*' },
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0007]/value',
            inputs: [{
              suffix: 'code',
              type: 'TEXT',
            }, {
              suffix: 'value',
              type: 'TEXT',
            }],
          }, {
            id: 'period_living_in_area',
            name: 'Period living in area',
            localizedName: 'Period living in area',
            rmType: 'DV_INTERVAL<DV_DATE_TIME>',
            nodeId: 'at0008',
            min: 0,
            max: 1,
            localizedNames: { en: 'Period living in area' },
            localizedDescriptions: { en: '*' },
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value',
            children: [{
              id: 'lower',
              rmType: 'DV_DATE_TIME',
              min: 1,
              max: 1,
              aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/lower',
              inputs: [{ type: 'DATETIME' }],
            }, {
              id: 'upper',
              rmType: 'DV_DATE_TIME',
              min: 1,
              max: 1,
              aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/upper',
              inputs: [{ type: 'DATETIME' }],
            }],
          }, {
            id: 'contact_with_birds',
            name: 'Contact with birds',
            localizedName: 'Contact with birds',
            rmType: 'DV_CODED_TEXT',
            nodeId: 'at0009',
            min: 0,
            max: 1,
            localizedNames: { en: 'Contact with birds' },
            localizedDescriptions: { en: '*' },
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0009]/value',
            inputs: [{
              suffix: 'code',
              type: 'CODED_TEXT',
              list: [{
                value: 'at0010',
                label: 'Yes',
                localizedLabels: { en: 'Yes' },
                localizedDescriptions: { en: '*' },
              }, {
                value: 'at0011',
                label: 'No',
                localizedLabels: { en: 'No' },
                localizedDescriptions: { en: '*' },
              }, {
                value: 'at0012',
                label: 'Unknown',
                localizedLabels: { en: 'Unknown' },
                localizedDescriptions: { en: '*' },
              }],
            }],
          }, {
            id: 'contact_with_avian_flu',
            name: 'Contact with avian flu',
            localizedName: 'Contact with avian flu',
            rmType: 'DV_CODED_TEXT',
            nodeId: 'at0013',
            min: 0,
            max: 1,
            localizedNames: { en: 'Contact with avian flu' },
            localizedDescriptions: { en: '*' },
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0013]/value',
            inputs: [{
              suffix: 'code',
              type: 'CODED_TEXT',
              list: [{
                value: 'at0014',
                label: 'Yes',
                localizedLabels: { en: 'Yes' },
                localizedDescriptions: { en: '*' },
              }, {
                value: 'at0015',
                label: 'No',
                localizedLabels: { en: 'No' },
                localizedDescriptions: { en: '*' },
              }, {
                value: 'at0016',
                label: 'Unknown',
                localizedLabels: { en: 'Unknown' },
                localizedDescriptions: { en: '*' },
              }],
            }],
          }, {
            id: 'contact_with_severe_unexplained_human_resp._illness',
            name: 'Contact with severe unexplained human resp. illness',
            localizedName: 'Contact with severe unexplained human resp. illness',
            rmType: 'DV_CODED_TEXT',
            nodeId: 'at0017',
            min: 0,
            max: 1,
            localizedNames: { en: 'Contact with severe unexplained human resp. illness' },
            localizedDescriptions: { en: '*' },
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0017]/value',
            inputs: [{
              suffix: 'code',
              type: 'TEXT',
            }, {
              suffix: 'value',
              type: 'TEXT',
            }],
          }],
        }],
      }, {
        id: 'time',
        name: 'Time',
        rmType: 'DV_DATE_TIME',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/time',
        inputs: [{ type: 'DATETIME' }],
        inContext: true,
      }, {
        id: 'language',
        name: 'Language',
        rmType: 'CODE_PHRASE',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/language',
        inContext: true,
      }, {
        id: 'encoding',
        name: 'Encoding',
        rmType: 'CODE_PHRASE',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/encoding',
        inContext: true,
      }, {
        id: 'subject',
        name: 'Subject',
        rmType: 'PARTY_PROXY',
        min: 1,
        max: 1,
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/subject',
        inContext: true,
      }],
    }],
  }, {
    id: 'category',
    rmType: 'DV_CODED_TEXT',
    min: 1,
    max: 1,
    aqlPath: '/category',
    inputs: [{
      suffix: 'code',
      type: 'CODED_TEXT',
      list: [{
        value: '433',
        label: 'event',
        localizedLabels: { en: 'event' },
      }],
      terminology: 'openehr',
    }],
    inContext: true,
  }, {
    id: 'language',
    name: 'Language',
    rmType: 'CODE_PHRASE',
    min: 1,
    max: 1,
    aqlPath: '/language',
    inContext: true,
  }, {
    id: 'territory',
    name: 'Territory',
    rmType: 'CODE_PHRASE',
    min: 1,
    max: 1,
    aqlPath: '/territory',
    inContext: true,
  }, {
    id: 'composer',
    name: 'Composer',
    rmType: 'PARTY_PROXY',
    min: 1,
    max: 1,
    aqlPath: '/composer',
    inContext: true,
  }],
};
export const resultAfterRunningFlat = [{
  name: 'who_-_suspected_covid-19_assessment.v0/context/start_time',
  key: 'who_-_suspected_covid-19_assessment.v0/context/start_time',
  label: 'Start_time',
  help: 'Contextual value',
  contextual: true,
  type: 'datetime',
  modifiers: {},
  validations: { required: true },
  aqlPath: '/context/start_time',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/context/setting',
  key: 'who_-_suspected_covid-19_assessment.v0/context/setting',
  label: 'Setting',
  help: 'Contextual value',
  contextual: true,
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: true },
  aqlPath: '/context/setting',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/reason_for_encounter/presenting_problem',
  key: 'who_-_suspected_covid-19_assessment.v0/reason_for_encounter/presenting_problem',
  label: 'Presenting problem',
  help: 'Identification of the clinical or social problem motivating the subject of care to seeking healthcare.',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0004]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/story',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/story',
  label: 'Story',
  help: 'Narrative description of the story or clinical history for the subject of care.',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/symptom_sign_name',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/symptom_sign_name',
  label: 'Symptom/Sign name',
  help: 'The name of the reported symptom or sign.',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0001]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/episode_onset',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/episode_onset',
  label: 'Episode onset',
  help: 'The onset for this episode of the symptom or sign.',
  type: 'datetime',
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0152]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/cough/nil_significant',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/cough/nil_significant',
  label: 'Nil significant',
  help: 'The identified symptom or sign was reported as not being present to any significant degree.',
  type: 'boolean',
  disabledValues: [],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']/items[at0035]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/fever/nil_significant',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/fever/nil_significant',
  label: 'Nil significant',
  help: 'The identified symptom or sign was reported as not being present to any significant degree.',
  type: 'boolean',
  disabledValues: [],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']/items[at0035]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/symptom_sign_name',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/symptom_sign_name',
  label: 'Symptom/Sign name',
  help: 'The name of the reported symptom or sign.',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0001]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/nil_significant',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/nil_significant',
  label: 'Nil significant',
  help: 'The identified symptom or sign was reported as not being present to any significant degree.',
  type: 'boolean',
  disabledValues: [],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0035]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/symptom_sign_name',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/symptom_sign_name',
  label: 'Symptom/Sign name',
  help: 'The name of the reported symptom or sign.',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0001]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/nil_significant',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/nil_significant',
  label: 'Nil significant',
  help: 'The identified symptom or sign was reported as not being present to any significant degree.',
  type: 'boolean',
  disabledValues: [],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0035]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/time',
  key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/time',
  label: 'Time',
  help: 'Contextual value',
  contextual: true,
  type: 'datetime',
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/time',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/duration_of_travel',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/duration_of_travel',
  label: 'Duration of travel',
  help: '*',
  type: 'number',
  modifiers: {},
  validations: {
    numberType: 'integer',
    required: false,
  },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0070]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/date_of_return_to_uk',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/date_of_return_to_uk',
  label: 'Date of return to UK',
  help: '*',
  type: 'datetime',
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0071,\'Date of return to UK\']/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/incubation_period',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/incubation_period',
  label: 'Incubation period',
  help: '*',
  type: 'number',
  modifiers: {},
  validations: {
    numberType: 'integer',
    required: false,
  },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0001]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/contact_with_confirmed_case|code',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/contact_with_confirmed_case',
  label: 'Contact with confirmed case',
  help: '*',
  type: 'options',
  inputOptions: [{
    value: 'at0003',
    label: 'Yes',
  }, {
    value: 'at0004',
    label: 'No',
  }, {
    value: 'at0005',
    label: 'Unknown',
  }],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0002]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/area',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/area',
  label: 'Area',
  help: '*',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0007]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/lower',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/lower',
  label: '',
  help: '',
  type: 'datetime',
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/lower',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/upper',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/upper',
  label: '',
  help: '',
  type: 'datetime',
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/upper',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_birds|code',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_birds',
  label: 'Contact with birds',
  help: '*',
  type: 'options',
  inputOptions: [{
    value: 'at0010',
    label: 'Yes',
  }, {
    value: 'at0011',
    label: 'No',
  }, {
    value: 'at0012',
    label: 'Unknown',
  }],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0009]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_avian_flu|code',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_avian_flu',
  label: 'Contact with avian flu',
  help: '*',
  type: 'options',
  inputOptions: [{
    value: 'at0014',
    label: 'Yes',
  }, {
    value: 'at0015',
    label: 'No',
  }, {
    value: 'at0016',
    label: 'Unknown',
  }],
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0013]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_severe_unexplained_human_resp._illness',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_severe_unexplained_human_resp._illness',
  label: 'Contact with severe unexplained human resp. illness',
  help: '*',
  suggestions: false,
  type: 'text',
  allowFreeText: true,
  modifiers: {},
  validations: { required: false },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0017]/value',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/time',
  key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/time',
  label: 'Time',
  help: 'Contextual value',
  contextual: true,
  type: 'datetime',
  modifiers: {},
  validations: { required: true },
  aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/time',
}, {
  name: 'who_-_suspected_covid-19_assessment.v0/category|code',
  key: 'who_-_suspected_covid-19_assessment.v0/category',
  label: 'category',
  help: 'Contextual value',
  contextual: true,
  type: 'options',
  inputOptions: [{
    value: '433',
    label: 'event',
  }],
  modifiers: {},
  validations: { required: true },
  aqlPath: '/category',
}];
export const resultAfterRunningStructured = {
  id: 'who_-_suspected_covid-19_assessment.v0',
  name: 'WHO - Suspected Covid-19'
    + ' assessment.v0',
  aqlPath: '',
  children: [{
    id: 'context',
    name: '',
    aqlPath: '/context',
    children: [{
      id: 'start_time',
      name: 'Start_time',
      aqlPath: '/context/start_time',
      inputs: {
        name: 'who_-_suspected_covid-19_assessment.v0/context/start_time',
        key: 'who_-_suspected_covid-19_assessment.v0/context/start_time',
        label: 'Start_time',
        help: 'Contextual value',
        contextual: true,
        type: 'datetime',
        modifiers: {},
        validations: { required: true },
      },
      aqlTrace: 'who_-_suspected_covid-19_assessment.v0/context/start_time',
      contextual: true,
    }, {
      id: 'setting',
      name: 'Setting',
      aqlPath: '/context/setting',
      inputs: {
        name: 'who_-_suspected_covid-19_assessment.v0/context/setting',
        key: 'who_-_suspected_covid-19_assessment.v0/context/setting',
        label: 'Setting',
        help: 'Contextual value',
        contextual: true,
        suggestions: false,
        type: 'text',
        allowFreeText: true,
        modifiers: {},
        validations: { required: true },
      },
      aqlTrace: 'who_-_suspected_covid-19_assessment.v0/context/setting',
      contextual: true,
    }],
  }, {
    id: 'reason_for_encounter',
    name: 'Reason for encounter',
    aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]',
    children: [{
      id: 'presenting_problem',
      name: 'Presenting problem',
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0004]/value',
      inputs: {
        name: 'who_-_suspected_covid-19_assessment.v0/reason_for_encounter/presenting_problem',
        key: 'who_-_suspected_covid-19_assessment.v0/reason_for_encounter/presenting_problem',
        label: 'Presenting problem',
        help: 'Identification of the clinical or social problem motivating the subject of care to seeking healthcare.',
        suggestions: false,
        type: 'text',
        allowFreeText: true,
        modifiers: {},
        validations: { required: false },
      },
      aqlTrace: 'who_-_suspected_covid-19_assessment.v0/reason_for_encounter/presenting_problem',
    }, {
      id: 'language',
      name: 'Language',
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/language',
      contextual: true,
    }, {
      id: 'encoding',
      name: 'Encoding',
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/encoding',
      contextual: true,
    }, {
      id: 'subject',
      name: 'Subject',
      aqlPath: '/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/subject',
      contextual: true,
    }],
  }, {
    id: 'symptoms',
    name: 'Symptoms',
    aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']',
    children: [{
      id: 'story_history',
      name: 'Story/History',
      aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]',
      children: [{
        id: 'story',
        name: 'Story',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value',
        inputs: {
          name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/story',
          key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/story',
          label: 'Story',
          help: 'Narrative description of the story or clinical history for the subject of care.',
          suggestions: false,
          type: 'text',
          allowFreeText: true,
          modifiers: {},
          validations: { required: false },
        },
        aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/story',
      }, {
        id: 'first_symptom',
        name: 'First symptom',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0001]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/symptom_sign_name',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/symptom_sign_name',
            label: 'Symptom/Sign name',
            help: 'The name of the reported symptom or sign.',
            suggestions: false,
            type: 'text',
            allowFreeText: true,
            modifiers: {},
            validations: { required: true },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/symptom_sign_name',
        }, {
          id: 'episode_onset',
          name: 'Episode onset',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'First symptom\']/items[at0152]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/episode_onset',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/episode_onset',
            label: 'Episode onset',
            help: 'The onset for this episode of the symptom or sign.',
            type: 'datetime',
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/first_symptom/episode_onset',
        }],
      }, {
        id: 'cough',
        name: 'Cough',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']/items[at0001]/value',
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Cough\']/items[at0035]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/cough/nil_significant',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/cough/nil_significant',
            label: 'Nil significant',
            help: 'The identified symptom or sign was reported as not being present to any significant degree.',
            type: 'boolean',
            disabledValues: [],
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/cough/nil_significant',
        }],
      }, {
        id: 'fever',
        name: 'Fever',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']/items[at0001]/value',
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Fever\']/items[at0035]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/fever/nil_significant',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/fever/nil_significant',
            label: 'Nil significant',
            help: 'The identified symptom or sign was reported as not being present to any significant degree.',
            type: 'boolean',
            disabledValues: [],
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/fever/nil_significant',
        }],
      }, {
        id: 'sore_throat',
        name: 'Sore throat',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0001]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/symptom_sign_name',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/symptom_sign_name',
            label: 'Symptom/Sign name',
            help: 'The name of the reported symptom or sign.',
            suggestions: false,
            type: 'text',
            allowFreeText: true,
            modifiers: {},
            validations: { required: true },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/symptom_sign_name',
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Sore throat\']/items[at0035]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/nil_significant',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/nil_significant',
            label: 'Nil significant',
            help: 'The identified symptom or sign was reported as not being present to any significant degree.',
            type: 'boolean',
            disabledValues: [],
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/sore_throat/nil_significant',
        }],
      }, {
        id: 'breathlessness',
        name: 'Breathlessness',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']',
        children: [{
          id: 'symptom_sign_name',
          name: 'Symptom/Sign name',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0001]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/symptom_sign_name',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/symptom_sign_name',
            label: 'Symptom/Sign name',
            help: 'The name of the reported symptom or sign.',
            suggestions: false,
            type: 'text',
            allowFreeText: true,
            modifiers: {},
            validations: { required: true },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/symptom_sign_name',
        }, {
          id: 'nil_significant',
          name: 'Nil significant',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.symptom_sign.v1,\'Breathlessness\']/items[at0035]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/nil_significant',
            key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/nil_significant',
            label: 'Nil significant',
            help: 'The identified symptom or sign was reported as not being present to any significant degree.',
            type: 'boolean',
            disabledValues: [],
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/breathlessness/nil_significant',
        }],
      }, {
        id: 'time',
        name: 'Time',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/time',
        inputs: {
          name: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/time',
          key: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/time',
          label: 'Time',
          help: 'Contextual value',
          contextual: true,
          type: 'datetime',
          modifiers: {},
          validations: { required: true },
        },
        aqlTrace: 'who_-_suspected_covid-19_assessment.v0/symptoms/story_history/time',
        contextual: true,
      }, {
        id: 'language',
        name: 'Language',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/language',
        contextual: true,
      }, {
        id: 'encoding',
        name: 'Encoding',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/encoding',
        contextual: true,
      }, {
        id: 'subject',
        name: 'Subject',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Symptoms\']/items[openEHR-EHR-OBSERVATION.story.v1]/subject',
        contextual: true,
      }],
    }],
  }, {
    id: 'travel_history',
    name: 'Travel history',
    aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']',
    children: [{
      id: 'trip_details',
      name: 'Trip details',
      aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]',
      children: [{
        id: 'duration_of_travel',
        name: 'Duration of travel',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0070]/value',
        inputs: {
          name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/duration_of_travel',
          key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/duration_of_travel',
          label: 'Duration of travel',
          help: '*',
          type: 'number',
          modifiers: {},
          validations: {
            numberType: 'integer',
            required: false,
          },
        },
        aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/duration_of_travel',
      }, {
        id: 'date_of_return_to_uk',
        name: 'Date of return to UK',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0071,\'Date of return to UK\']/value',
        inputs: {
          name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/date_of_return_to_uk',
          key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/date_of_return_to_uk',
          label: 'Date of return to UK',
          help: '*',
          type: 'datetime',
          modifiers: {},
          validations: { required: false },
        },
        aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/date_of_return_to_uk',
      }, {
        id: 'covid19_exposure',
        name: 'Covid19 exposure',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]',
        children: [{
          id: 'incubation_period',
          name: 'Incubation period',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0001]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/incubation_period',
            key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/incubation_period',
            label: 'Incubation period',
            help: '*',
            type: 'number',
            modifiers: {},
            validations: {
              numberType: 'integer',
              required: false,
            },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/incubation_period',
        }, {
          id: 'contact_with_confirmed_case',
          name: 'Contact with confirmed case',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0002]/value',
          inputs: {
            name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/contact_with_confirmed_case|code',
            key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/contact_with_confirmed_case',
            label: 'Contact with confirmed case',
            help: '*',
            type: 'options',
            inputOptions: [{
              value: 'at0003',
              label: 'Yes',
            }, {
              value: 'at0004',
              label: 'No',
            }, {
              value: 'at0005',
              label: 'Unknown',
            }],
            modifiers: {},
            validations: { required: false },
          },
          aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/contact_with_confirmed_case',
        }, {
          id: 'outbreak',
          name: 'Outbreak',
          aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]',
          children: [{
            id: 'area',
            name: 'Area',
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0007]/value',
            inputs: {
              name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/area',
              key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/area',
              label: 'Area',
              help: '*',
              suggestions: false,
              type: 'text',
              allowFreeText: true,
              modifiers: {},
              validations: { required: false },
            },
            aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/area',
          }, {
            id: 'period_living_in_area',
            name: 'Period living in area',
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value',
            children: [{
              id: 'lower',
              name: '',
              aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/lower',
              inputs: {
                name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/lower',
                key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/lower',
                label: '',
                help: '',
                type: 'datetime',
                modifiers: {},
                validations: { required: true },
              },
              aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/lower',
            }, {
              id: 'upper',
              name: '',
              aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0008]/value/upper',
              inputs: {
                name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/upper',
                key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/upper',
                label: '',
                help: '',
                type: 'datetime',
                modifiers: {},
                validations: { required: true },
              },
              aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/period_living_in_area/upper',
            }],
          }, {
            id: 'contact_with_birds',
            name: 'Contact with birds',
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0009]/value',
            inputs: {
              name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_birds|code',
              key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_birds',
              label: 'Contact with birds',
              help: '*',
              type: 'options',
              inputOptions: [{
                value: 'at0010',
                label: 'Yes',
              }, {
                value: 'at0011',
                label: 'No',
              }, {
                value: 'at0012',
                label: 'Unknown',
              }],
              modifiers: {},
              validations: { required: false },
            },
            aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_birds',
          }, {
            id: 'contact_with_avian_flu',
            name: 'Contact with avian flu',
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0013]/value',
            inputs: {
              name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_avian_flu|code',
              key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_avian_flu',
              label: 'Contact with avian flu',
              help: '*',
              type: 'options',
              inputOptions: [{
                value: 'at0014',
                label: 'Yes',
              }, {
                value: 'at0015',
                label: 'No',
              }, {
                value: 'at0016',
                label: 'Unknown',
              }],
              modifiers: {},
              validations: { required: false },
            },
            aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_avian_flu',
          }, {
            id: 'contact_with_severe_unexplained_human_resp._illness',
            name: 'Contact with severe unexplained human resp. illness',
            aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.covid19_exposure.v0]/items[at0006]/items[at0017]/value',
            inputs: {
              name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_severe_unexplained_human_resp._illness',
              key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_severe_unexplained_human_resp._illness',
              label: 'Contact with severe unexplained human resp. illness',
              help: '*',
              suggestions: false,
              type: 'text',
              allowFreeText: true,
              modifiers: {},
              validations: { required: false },
            },
            aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/covid19_exposure/outbreak/contact_with_severe_unexplained_human_resp._illness',
          }],
        }],
      }, {
        id: 'time',
        name: 'Time',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/data[at0001]/events[at0002]/time',
        inputs: {
          name: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/time',
          key: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/time',
          label: 'Time',
          help: 'Contextual value',
          contextual: true,
          type: 'datetime',
          modifiers: {},
          validations: { required: true },
        },
        aqlTrace: 'who_-_suspected_covid-19_assessment.v0/travel_history/trip_details/time',
        contextual: true,
      }, {
        id: 'language',
        name: 'Language',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/language',
        contextual: true,
      }, {
        id: 'encoding',
        name: 'Encoding',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/encoding',
        contextual: true,
      }, {
        id: 'subject',
        name: 'Subject',
        aqlPath: '/content[openEHR-EHR-SECTION.adhoc.v1,\'Travel history\']/items[openEHR-EHR-OBSERVATION.travel_history.v0]/subject',
        contextual: true,
      }],
    }],
  }, {
    id: 'category',
    name: '',
    aqlPath: '/category',
    inputs: {
      name: 'who_-_suspected_covid-19_assessment.v0/category|code',
      key: 'who_-_suspected_covid-19_assessment.v0/category',
      label: 'category',
      help: 'Contextual value',
      contextual: true,
      type: 'options',
      inputOptions: [{
        value: '433',
        label: 'event',
      }],
      modifiers: {},
      validations: { required: true },
    },
    aqlTrace: 'who_-_suspected_covid-19_assessment.v0/category',
    contextual: true,
  }, {
    id: 'language',
    name: 'Language',
    aqlPath: '/language',
    contextual: true,
  }, {
    id: 'territory',
    name: 'Territory',
    aqlPath: '/territory',
    contextual: true,
  }, {
    id: 'composer',
    name: 'Composer',
    aqlPath: '/composer',
    contextual: true,
  }],
};
